name: filmguru
description: Netguru Flutter recrutation app
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  fvm: ^2.2.6
  json_annotation: ^4.4.0
  provider: ^6.0.2
  rxdart: ^0.27.3

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  build_test: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  mockito: ^5.0.17

flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json

flutter_intl:
  enabled: true
